// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtS42vOJrBfLUxGF5viQ4GJLXBvwaf-hU',
    appId: '1:21940943998:web:3963c6b5c506bc36ffec2f',
    messagingSenderId: '21940943998',
    projectId: 'mddprod-2954f',
    authDomain: 'mddprod-2954f.firebaseapp.com',
    storageBucket: 'mddprod-2954f.firebasestorage.app',
    measurementId: 'G-P6RF58880H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmj3qZ0jDGNgOkOSfQfaDg8_JY1RpidQc',
    appId: '1:21940943998:android:5d4e9804bd194932ffec2f',
    messagingSenderId: '21940943998',
    projectId: 'mddprod-2954f',
    storageBucket: 'mddprod-2954f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMlLpbssXzm_3HZLatACPvuH74hrkVk6U',
    appId: '1:21940943998:ios:900654675dbbe5efffec2f',
    messagingSenderId: '21940943998',
    projectId: 'mddprod-2954f',
    storageBucket: 'mddprod-2954f.firebasestorage.app',
    androidClientId: '21940943998-mm6knl250u8vlmv6kak7t0haaee3mt4r.apps.googleusercontent.com',
    iosClientId: '21940943998-03bqidg017cpvqiosi534aa0rs4b9gau.apps.googleusercontent.com',
    iosBundleId: 'com.example.waiter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMlLpbssXzm_3HZLatACPvuH74hrkVk6U',
    appId: '1:21940943998:ios:900654675dbbe5efffec2f',
    messagingSenderId: '21940943998',
    projectId: 'mddprod-2954f',
    storageBucket: 'mddprod-2954f.firebasestorage.app',
    androidClientId: '21940943998-mm6knl250u8vlmv6kak7t0haaee3mt4r.apps.googleusercontent.com',
    iosClientId: '21940943998-03bqidg017cpvqiosi534aa0rs4b9gau.apps.googleusercontent.com',
    iosBundleId: 'com.example.waiter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtS42vOJrBfLUxGF5viQ4GJLXBvwaf-hU',
    appId: '1:21940943998:web:0fe09b49b39982b9ffec2f',
    messagingSenderId: '21940943998',
    projectId: 'mddprod-2954f',
    authDomain: 'mddprod-2954f.firebaseapp.com',
    storageBucket: 'mddprod-2954f.firebasestorage.app',
    measurementId: 'G-NHEV00GH4H',
  );
}
